### ISSUE TITLE
Programar el botón para buscar las preguntas de recuperar contraseña

### ISSUE THREAD

**Issue by srrendo** [srrendo/Clase9#6]
Validar que se ingrese el documento del usuario al cual se le va a recuperar la contraseña, validar que el documento sea númerico, crear la clase usuarios con sus 11 propiedades, solo considerar una contraseña, buscar las preguntas para recuperar la contraseña .

**Comment by srrendon** [comment]
Me voy a encargar de esta tarea.

**Comment by srrendo** [comment]
Listo, quedo pendiente del primero Push
